In [35]:
import pandas as pd 
import numpy as np

In [36]:
df = pd.read_csv("8-apply_function_data.csv")

In [37]:
df

    Employee_ID     Name Department  Salary  Experience  Performance_Score
0             1    Emp_1  Marketing   82251           6                  5
1             2    Emp_2      Sales   52662          24                  3
2             3    Emp_3    Finance   38392           5                  3
3             4    Emp_4      Sales   60535          20                  3
4             5    Emp_5      Sales  108603           2                  2
..          ...      ...        ...     ...         ...                ...
95           96   Emp_96    Finance   93734          19                  4
96           97   Emp_97      Sales  100467          22                  2
97           98   Emp_98         IT   82662          23                  3
98           99   Emp_99         IT   42688          22                  1
99          100  Emp_100         HR   55342          14                  3

[100 rows x 6 columns]

In [38]:
def salary_category(salary):
    if salary < 50000:
        return "Low"
    elif 50000 <= salary < 80000:
        return "Medium"
    else:
        return "High"

In [39]:
df["Salary_Category"] = df["Salary"].apply(salary_category)

In [40]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category
0,1,Emp_1,Marketing,82251,6,5,High
1,2,Emp_2,Sales,52662,24,3,Medium
2,3,Emp_3,Finance,38392,5,3,Low
3,4,Emp_4,Sales,60535,20,3,Medium
4,5,Emp_5,Sales,108603,2,2,High
...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High
96,97,Emp_97,Sales,100467,22,2,High
97,98,Emp_98,IT,82662,23,3,High
98,99,Emp_99,IT,42688,22,1,Low
99,100,Emp_100,HR,55342,14,3,Medium

In [41]:
def adjust_new(row):
    if row["Experience"] > 10:
        return row["Performance_Score"] + 1
    else:
        row["Performance_Score"]

In [42]:
df["New_Performance_Score"] = df.apply(adjust_new , axis=1)

In [43]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,New_Performance_Score
0,1,Emp_1,Marketing,82251,6,5,High,NaN
1,2,Emp_2,Sales,52662,24,3,Medium,4.0
2,3,Emp_3,Finance,38392,5,3,Low,NaN
3,4,Emp_4,Sales,60535,20,3,Medium,4.0
4,5,Emp_5,Sales,108603,2,2,High,NaN
...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,5.0
96,97,Emp_97,Sales,100467,22,2,High,3.0
97,98,Emp_98,IT,82662,23,3,High,4.0
98,99,Emp_99,IT,42688,22,1,Low,2.0
99,100,Emp_100,HR,55342,14,3,Medium,4.0

In [44]:
df["New_Name"] = df["Name"].apply(lambda x : x.replace("_"," "))

In [45]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,New_Performance_Score,New_Name
0,1,Emp_1,Marketing,82251,6,5,High,NaN,Emp 1
1,2,Emp_2,Sales,52662,24,3,Medium,4.0,Emp 2
2,3,Emp_3,Finance,38392,5,3,Low,NaN,Emp 3
3,4,Emp_4,Sales,60535,20,3,Medium,4.0,Emp 4
4,5,Emp_5,Sales,108603,2,2,High,NaN,Emp 5
...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,5.0,Emp 96
96,97,Emp_97,Sales,100467,22,2,High,3.0,Emp 97
97,98,Emp_98,IT,82662,23,3,High,4.0,Emp 98
98,99,Emp_99,IT,42688,22,1,Low,2.0,Emp 99
99,100,Emp_100,HR,55342,14,3,Medium,4.0,Emp 100

In [48]:
df["New_Performance_Score"].fillna(df["Performance_Score"])

0     5.0
1     4.0
2     3.0
3     4.0
4     2.0
     ...
95    5.0
96    3.0
97    4.0
98    2.0
99    4.0
Name: New_Performance_Score, Length: 100, dtype: float64

In [49]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,New_Performance_Score,New_Name
0,1,Emp_1,Marketing,82251,6,5,High,5.0,Emp 1
1,2,Emp_2,Sales,52662,24,3,Medium,4.0,Emp 2
2,3,Emp_3,Finance,38392,5,3,Low,3.0,Emp 3
3,4,Emp_4,Sales,60535,20,3,Medium,4.0,Emp 4
4,5,Emp_5,Sales,108603,2,2,High,2.0,Emp 5
...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,5.0,Emp 96
96,97,Emp_97,Sales,100467,22,2,High,3.0,Emp 97
97,98,Emp_98,IT,82662,23,3,High,4.0,Emp 98
98,99,Emp_99,IT,42688,22,1,Low,2.0,Emp 99
99,100,Emp_100,HR,55342,14,3,Medium,4.0,Emp 100

In [58]:
grouped = df.groupby("Department")

In [60]:
grouped.describe()

           Employee_ID                                                         \
                 count       mean        std   min    25%   50%    75%    max
Department
Finance           16.0  44.625000  36.103324   3.0  11.25  33.0  90.25   96.0
HR                18.0  63.777778  27.817801  19.0  39.75  74.0  86.75  100.0
IT                21.0  52.380952  25.535223   6.0  40.00  58.0  67.00   99.0
Marketing         26.0  46.538462  24.073605   1.0  29.25  50.5  65.00   89.0
Sales             19.0  46.210526  32.085959   2.0  15.50  48.0  74.00   97.0

           Salary                ... Performance_Score       \
            count          mean  ...               75%  max
Department                       ...
Finance      16.0  81011.812500  ...              4.25  5.0
HR           18.0  87695.333333  ...              4.00  5.0
IT           21.0  60994.190476  ...              4.00  5.0
Marketing    26.0  82930.807692  ...              4.00  5.0
Sales        19.0  75738.157895  ...              3.50  5.0

           New_Performance_Score
                           count      mean       std  min  25%  50%  75%  max
Department
Finance                     16.0  3.562500  1.590335  1.0  2.0  4.0  5.0  6.0
HR                          18.0  3.666667  1.495090  1.0  3.0  4.0  5.0  6.0
IT                          21.0  3.619048  1.657594  1.0  2.0  3.0  5.0  6.0
Marketing                   26.0  3.692308  1.435806  1.0  3.0  4.0  5.0  6.0
Sales                       19.0  3.263158  1.593114  1.0  2.0  3.0  4.0  6.0

[5 rows x 40 columns]

In [64]:
grouped["Salary"].mean()

Department
Finance      81011.812500
HR           87695.333333
IT           60994.190476
Marketing    82930.807692
Sales        75738.157895
Name: Salary, dtype: float64

In [65]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,New_Performance_Score,New_Name
0,1,Emp_1,Marketing,82251,6,5,High,5.0,Emp 1
1,2,Emp_2,Sales,52662,24,3,Medium,4.0,Emp 2
2,3,Emp_3,Finance,38392,5,3,Low,3.0,Emp 3
3,4,Emp_4,Sales,60535,20,3,Medium,4.0,Emp 4
4,5,Emp_5,Sales,108603,2,2,High,2.0,Emp 5
...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,5.0,Emp 96
96,97,Emp_97,Sales,100467,22,2,High,3.0,Emp 97
97,98,Emp_98,IT,82662,23,3,High,4.0,Emp 98
98,99,Emp_99,IT,42688,22,1,Low,2.0,Emp 99
99,100,Emp_100,HR,55342,14,3,Medium,4.0,Emp 100

In [76]:
def new_salary(row):
    if row["Performance_Score"] < 4:
        return row["Salary"] * 1.2
    elif row["Performance_Score"] >= 4:
        return row["Salary"] * 1.1 
    else:
        return row["Salary"]

In [77]:
df["New_Salary"] = df.apply(new_salary , axis=1)

In [78]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,New_Performance_Score,New_Name,New_Salary
0,1,Emp_1,Marketing,82251,6,5,High,5.0,Emp 1,90476.1
1,2,Emp_2,Sales,52662,24,3,Medium,4.0,Emp 2,63194.4
2,3,Emp_3,Finance,38392,5,3,Low,3.0,Emp 3,46070.4
3,4,Emp_4,Sales,60535,20,3,Medium,4.0,Emp 4,72642.0
4,5,Emp_5,Sales,108603,2,2,High,2.0,Emp 5,130323.6
...,...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,5.0,Emp 96,103107.4
96,97,Emp_97,Sales,100467,22,2,High,3.0,Emp 97,120560.4
97,98,Emp_98,IT,82662,23,3,High,4.0,Emp 98,99194.4
98,99,Emp_99,IT,42688,22,1,Low,2.0,Emp 99,51225.6
99,100,Emp_100,HR,55342,14,3,Medium,4.0,Emp 100,66410.4

In [79]:
def tecrubee(row):
    if row["Experience"] <= 5:
        return "Junior"
    elif 5 < row["Experience"] <= 15:
        return "Mid-Senior"
    elif row["Experience"] > 15:
        return "Senior"
    else:
        return "Noob"

In [80]:
df["Experience_Level"] = df.apply(tecrubee , axis=1)

In [81]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,New_Performance_Score,New_Name,New_Salary,Experience_Level
0,1,Emp_1,Marketing,82251,6,5,High,5.0,Emp 1,90476.1,Mid-Senior
1,2,Emp_2,Sales,52662,24,3,Medium,4.0,Emp 2,63194.4,Senior
2,3,Emp_3,Finance,38392,5,3,Low,3.0,Emp 3,46070.4,Junior
3,4,Emp_4,Sales,60535,20,3,Medium,4.0,Emp 4,72642.0,Senior
4,5,Emp_5,Sales,108603,2,2,High,2.0,Emp 5,130323.6,Junior
...,...,...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,5.0,Emp 96,103107.4,Senior
96,97,Emp_97,Sales,100467,22,2,High,3.0,Emp 97,120560.4,Senior
97,98,Emp_98,IT,82662,23,3,High,4.0,Emp 98,99194.4,Senior
98,99,Emp_99,IT,42688,22,1,Low,2.0,Emp 99,51225.6,Senior
99,100,Emp_100,HR,55342,14,3,Medium,4.0,Emp 100,66410.4,Mid-Senior

In [101]:
df[(df["Salary"] > 80000) & (df["Experience_Level"] == "Senior")]

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,New_Performance_Score,New_Name,New_Salary,Experience_Level
6,7,Emp_7,Finance,119135,22,1,High,2.0,Emp 7,142962.0,Senior
8,9,Emp_9,Finance,107373,16,1,High,2.0,Emp 9,128847.6,Senior
9,10,Emp_10,Sales,109575,16,5,High,6.0,Emp 10,120532.5,Senior
19,20,Emp_20,Marketing,112948,19,5,High,6.0,Emp 20,124242.8,Senior
22,23,Emp_23,Marketing,117054,20,4,High,5.0,Emp 23,128759.4,Senior
27,28,Emp_28,IT,84268,18,5,High,6.0,Emp 28,92694.8,Senior
31,32,Emp_32,Marketing,101910,18,4,High,5.0,Emp 32,112101.0,Senior
32,33,Emp_33,Marketing,86044,23,5,High,6.0,Emp 33,94648.4,Senior
36,37,Emp_37,Finance,92623,16,2,High,3.0,Emp 37,111147.6,Senior
37,38,Emp_38,Sales,111734,16,1,High,2.0,Emp 38,134080.8,Senior
38,39,Emp_39,HR,105450,20,2,High,3.0,Emp 39,126540.0,Senior
52,53,Emp_53,Marketing,105766,16,2,High,3.0,Emp 53,126919.2,Senior
59,60,Emp_60,IT,91373,24,2,High,3.0,Emp 60,109647.6,Senior
71,72,Emp_72,Sales,91087,18,1,High,2.0,Emp 72,109304.4,Senior
73,74,Emp_74,IT,84384,18,5,High,6.0,Emp 74,92822.4,Senior
77,78,Emp_78,Marketing,92003,16,4,High,5.0,Emp 78,101203.3,Senior
84,85,Emp_85,HR,115616,21,4,High,5.0,Emp 85,127177.6,Senior
91,92,Emp_92,HR,117092,17,3,High,4.0,Emp 92,140510.4,Senior
95,96,Emp_96,Finance,93734,19,4,High,5.0,Emp 96,103107.4,Senior
96,97,Emp_97,Sales,100467,22,2,High,3.0,Emp 97,120560.4,Senior
97,98,Emp_98,IT,82662,23,3,High,4.0,Emp 98,99194.4,Senior

In [102]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,New_Performance_Score,New_Name,New_Salary,Experience_Level
0,1,Emp_1,Marketing,82251,6,5,High,5.0,Emp 1,90476.1,Mid-Senior
1,2,Emp_2,Sales,52662,24,3,Medium,4.0,Emp 2,63194.4,Senior
2,3,Emp_3,Finance,38392,5,3,Low,3.0,Emp 3,46070.4,Junior
3,4,Emp_4,Sales,60535,20,3,Medium,4.0,Emp 4,72642.0,Senior
4,5,Emp_5,Sales,108603,2,2,High,2.0,Emp 5,130323.6,Junior
...,...,...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,5.0,Emp 96,103107.4,Senior
96,97,Emp_97,Sales,100467,22,2,High,3.0,Emp 97,120560.4,Senior
97,98,Emp_98,IT,82662,23,3,High,4.0,Emp 98,99194.4,Senior
98,99,Emp_99,IT,42688,22,1,Low,2.0,Emp 99,51225.6,Senior
99,100,Emp_100,HR,55342,14,3,Medium,4.0,Emp 100,66410.4,Mid-Senior

In [104]:
df[(df["Salary"] > 90000) & (df["Performance_Score"] < 3 )]

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,New_Performance_Score,New_Name,New_Salary,Experience_Level
4,5,Emp_5,Sales,108603,2,2,High,2.0,Emp 5,130323.6,Junior
6,7,Emp_7,Finance,119135,22,1,High,2.0,Emp 7,142962.0,Senior
8,9,Emp_9,Finance,107373,16,1,High,2.0,Emp 9,128847.6,Senior
16,17,Emp_17,Marketing,109309,4,1,High,1.0,Emp 17,131170.8,Junior
23,24,Emp_24,HR,117897,9,1,High,1.0,Emp 24,141476.4,Mid-Senior
30,31,Emp_31,Finance,110356,11,1,High,2.0,Emp 31,132427.2,Mid-Senior
36,37,Emp_37,Finance,92623,16,2,High,3.0,Emp 37,111147.6,Senior
37,38,Emp_38,Sales,111734,16,1,High,2.0,Emp 38,134080.8,Senior
38,39,Emp_39,HR,105450,20,2,High,3.0,Emp 39,126540.0,Senior
41,42,Emp_42,HR,94044,1,2,High,2.0,Emp 42,112852.8,Junior
45,46,Emp_46,HR,99163,5,2,High,2.0,Emp 46,118995.6,Junior
52,53,Emp_53,Marketing,105766,16,2,High,3.0,Emp 53,126919.2,Senior
59,60,Emp_60,IT,91373,24,2,High,3.0,Emp 60,109647.6,Senior
68,69,Emp_69,Marketing,96199,3,2,High,2.0,Emp 69,115438.8,Junior
71,72,Emp_72,Sales,91087,18,1,High,2.0,Emp 72,109304.4,Senior
72,73,Emp_73,Sales,98840,14,2,High,3.0,Emp 73,118608.0,Mid-Senior
78,79,Emp_79,Marketing,113211,9,2,High,2.0,Emp 79,135853.2,Mid-Senior
94,95,Emp_95,HR,117455,12,2,High,3.0,Emp 95,140946.0,Mid-Senior
96,97,Emp_97,Sales,100467,22,2,High,3.0,Emp 97,120560.4,Senior

In [113]:
yeni_veri = {

    "Department" : ["Marketing","Sales","Finance","HR","IT"],
    "Location" : ["Istanbul", "Ankara" , "Istanbul" , "Izmir" , "Ankara"]    
}

In [114]:
yeni_veri

{'Department': ['Marketing', 'Sales', 'Finance', 'HR', 'IT'],
 'Location': ['Istanbul', 'Ankara', 'Istanbul', 'Izmir', 'Ankara']}

In [115]:
df_lokasyon = pd.DataFrame(yeni_veri)

In [116]:
df_lokasyon

  Department  Location
0  Marketing  Istanbul
1      Sales    Ankara
2    Finance  Istanbul
3         HR     Izmir
4         IT    Ankara

In [117]:
pd.merge(df, df_lokasyon, on="Department", how= "left")

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,New_Performance_Score,New_Name,New_Salary,Experience_Level,Location
0,1,Emp_1,Marketing,82251,6,5,High,5.0,Emp 1,90476.1,Mid-Senior,Istanbul
1,2,Emp_2,Sales,52662,24,3,Medium,4.0,Emp 2,63194.4,Senior,Ankara
2,3,Emp_3,Finance,38392,5,3,Low,3.0,Emp 3,46070.4,Junior,Istanbul
3,4,Emp_4,Sales,60535,20,3,Medium,4.0,Emp 4,72642.0,Senior,Ankara
4,5,Emp_5,Sales,108603,2,2,High,2.0,Emp 5,130323.6,Junior,Ankara
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,5.0,Emp 96,103107.4,Senior,Istanbul
96,97,Emp_97,Sales,100467,22,2,High,3.0,Emp 97,120560.4,Senior,Ankara
97,98,Emp_98,IT,82662,23,3,High,4.0,Emp 98,99194.4,Senior,Ankara
98,99,Emp_99,IT,42688,22,1,Low,2.0,Emp 99,51225.6,Senior,Ankara
99,100,Emp_100,HR,55342,14,3,Medium,4.0,Emp 100,66410.4,Mid-Senior,Izmir

In [122]:
sales = {
    "Employee_ID" : [2, 4, 5, 96] ,
    "Sales" : [150000, 95000, 210000, 130000]
}

In [123]:
df_sales = pd.DataFrame(sales)

In [124]:
df_sales

   Employee_ID   Sales
0            2  150000
1            4   95000
2            5  210000
3           96  130000

In [129]:
pd.merge(df, df_sales , on="Employee_ID", how= "inner" )

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,New_Performance_Score,New_Name,New_Salary,Experience_Level,Sales
0,2,Emp_2,Sales,52662,24,3,Medium,4.0,Emp 2,63194.4,Senior,150000
1,4,Emp_4,Sales,60535,20,3,Medium,4.0,Emp 4,72642.0,Senior,95000
2,5,Emp_5,Sales,108603,2,2,High,2.0,Emp 5,130323.6,Junior,210000
3,96,Emp_96,Finance,93734,19,4,High,5.0,Emp 96,103107.4,Senior,130000